STATIC_CONF_PATH = "static-configurations"
BUILD_PATH = "build/"

VAULT_MOUNTS_PATH = "sys/mounts"
VAULT_POLICIES_PATH = "sys/policy"

VAULT_TEAMS_MOUNT = "teams/"

VAULT_DATA_KEY = "data"

VAULT_ROTATE_SUFFIX_UNIT_DAYS = "d"
VAULT_ROTATE_SUFFIX_UNIT_HOURS = "h"
VAULT_ROTATE_SUFFIX_FORMAT = "-{number}{unit}"

VAULT_VERSIONNED_KV_DATA = "data"
VAULT_VERSIONNED_KV_METADATA = "metadata"
VAULT_VERSIONNED_KV_DELETE = "delete"
VAULT_VERSIONNED_KV_DESTROY = "destroy"
VAULT_VERSIONNED_KV_UNDELETE = "undelete"

VAULT_VERSIONNED_KV_KEYWORDS = [VAULT_VERSIONNED_KV_METADATA, VAULT_VERSIONNED_KV_DATA, VAULT_VERSIONNED_KV_DELETE,
                                VAULT_VERSIONNED_KV_UNDELETE, VAULT_VERSIONNED_KV_DESTROY]
